'use client';

import { useActionState } from 'react';
import { startEnrollment, verifyCode, type EnrollState } from './actions';

export function EnrollForm() {
  const [state, start, pending] = useActionState(startEnrollment, null as EnrollState);
  if (state && 'factorId' in state) {
    return (
      <>
        <p>Scan this code with your authenticator app, or enter the secret manually: <code>{state.secret}</code></p>
        {/* qr_code is an SVG data URI generated by Supabase Auth */}
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img src={state.qr} alt="Authenticator setup QR code" width={200} height={200} />
        <form action={verifyCode}>
          <input type="hidden" name="factor" value={state.factorId} />
          <label>6-digit code <input name="code" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9 ]{6,7}" required /></label>
          <button type="submit">Verify and finish setup</button>
        </form>
      </>
    );
  }
  return (
    <form action={start}>
      <p>Administrator access requires an authenticator app (TOTP). Set one up now.</p>
      {state && 'error' in state ? <p role="alert">{state.error}</p> : null}
      <button type="submit" disabled={pending}>{pending ? 'Starting…' : 'Set up authenticator'}</button>
    </form>
  );
}
